apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: s3-webhook-workflows-templates
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: s3-list
      eventSourceName: webhook
      eventName: example
      filters:
        data:
          - path: body.message
            type: string
            value:
              - "lists3"
    - name: s3-list-v2
      eventSourceName: webhook
      eventName: example1
      filters:
        data:
          - path: body.message
            type: string
            value:
              - "lists3v2"
  triggers:
    - template:
        conditions: "s3-list"
        name: s3-webhook-workflow-trigger-v1
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: s3-
              spec:
                workflowTemplateRef:
                  name: s3-list
    - template:
        conditions: "s3-list-v2"
        name: s3-webhook-workflow-trigger-v2
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: s3-v2-
              spec:
                workflowTemplateRef:
                  name: s3-listv2
      parameters:
        - src:
            dependencyName: s3-list
            dataKey: body
          dest: spec.arguments.parameters.0.value
        - src:
            dependencyName: s3-list-v2
            dataKey: body
          dest: spec.arguments.parameters.0.value         
