# argo-chaos-workflows-server-cluster-template-cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-chaos-workflows-server-cluster-template
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-chaos-workflows-server
subjects:
- kind: ServiceAccount
  name: argo-argo-workflows-server
  namespace: argo
- kind: ServiceAccount
  name: argo-argo-workflows-workflow-controller
  namespace: argo

