# argo-chaos-workflows-server-cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-chaos-workflows-server
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

