apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: chaos-mesh-workflow-template
spec:
  templates:
    - name: chaos-mesh-workflow
      chaos:
        manifest: |
          apiVersion: chaos-mesh.org/v1alpha1
          kind: Workflow
          metadata:
            name: serial-payment-stress-mysql-podkill-order-stress
            namespace: trino-test
          spec:
            entry: entry
            templates:
              - name: entry
                templateType: Serial
                deadline: 12m
                children:
                  - payment-stress
                  - parallel-load
              - name: payment-stress
                templateType: StressChaos
                deadline: 3m
                stressChaos:
                  selector:
                    namespaces:
                      - trino-test
                    labelSelectors:
                      run: tomcat
                  mode: all
                  stressors:
                    memory:
                      workers: 150
                    cpu:
                      workers: 150
                      load: 100
              - name: parallel-load
                templateType: Parallel
                children:
                  - mysql-podkill
                  - order-stress
              - name: mysql-podkill
                templateType: PodChaos
                podChaos:
                  selector:
                    namespaces:
                      - trino-test
                    labelSelectors:
                      run: tomcat
                  mode: all
                  action: pod-kill
              - name: order-stress
                templateType: StressChaos
                deadline: 8m
                stressChaos:
                  selector:
                    namespaces:
                      - trino-test
                    labelSelectors:
                      run: tomcat
                  annotationSelectors:
                    kubectl.kubernetes.io/default-container: tomcat
                  mode: all
                  stressors:
                    memory:
                      workers: 200
                    cpu:
                      workers: 200
                      load: 100
