# chaos-mesh-template.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: chaos-mesh-pod-kill-template
spec:
  templates:
    - name: chaos-mesh-pod-kill
      podChaos:
        action: pod-kill
        mode: one
        selector:
          namespaces:
            - 'trino-test'
          labelSelectors:
            'run': 'tomcat'

