apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: slack
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: slack
      eventName: example-insecure
  triggers:
    - template:
        name: slack-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: slack-
              spec:
                entrypoint: clear-s3
                serviceAccountName: operate-workflow-sa
                arguments:
                  parameters:
                  - name: message
                    value: ""
                templates:
                  - container:
                      args:
                        - >-
                          aws s3 rm s3://test-s3-bucket-clen --recursive
                          --region us-east-1
                      command:
                        - sh
                        - '-c'
                      env:
                        - name: AWS_ACCESS_KEY_ID
                          valueFrom:
                            secretKeyRef:
                              key: access_key
                              name: aws-secret
                        - name: AWS_SECRET_ACCESS_KEY
                          valueFrom:
                            secretKeyRef:
                              key: secret_key
                              name: aws-secret
                    name: clear-s3
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.message
              dest: spec.arguments.parameters.0.value

