apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: slack-sensor
spec:
  template:
    spec:
      containers:
        - name: aws-cli
          image: amazon/aws-cli
          command:
            - "sh"
            - "-c"
            - "aws s3 rm s3://test-s3-bucket-clen/* --region us-east-1 --recursive"
          env:
            - name: AWS_ACCESS_KEY_ID 
              value: AKIA4GSKCISGRP7JBG5X 
            - name: AWS_SECRET_ACCESS_KEY 
              value: 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
  dependencies:
    - name: slack
      gatewayName: slack-gateway
      eventSourceName: slack-event-source
      eventName: message
      filters:
        - name: slack-message-filter
          type: jmespath
          expr: slack.event.channel == '#argo-events-channel' && slack.event.text == 'clear s3'
  triggers:
    - template:
        name: clear-s3
        dag:
          tasks:
            - name: clear-s3-task
              template: aws-cli
        arguments:
          parameters:
            - name: bucket-name
              value: test-s3-bucket
      when: "dependencies.slack.outputs.parameters.message != ''"

